version: 2.1

parameters:
  workingdir:
    type: string
    default: "~/main"

executors:
  my-executor:
    resource_class: small
    docker:
      - image: cimg/base:2022.09

jobs:
  build:
    executor: my-executor
    working_directory: << pipeline.parameters.workingdir >>

    steps:
      - checkout
      - run:
          name: "Add build time to index file"
          command: date >> index.html

      - persist_to_workspace:
          root: << pipeline.parameters.workingdir >>
          paths:
            - ./
  deploy:
    executor: my-executor
    steps:
      - attach_workspace:
          at: << pipeline.parameters.workingdir >>
      - run: mkdir -p ~/.ssh
      - run:
          name: Add ssh key
          command: |
            # Decode the key in base64 format to be used in a new ssh key file
            echo $SSH_KEY_KEY_BASE64 | base64 -d >> ~/.ssh/$SSH_KEY_ID

            # Update the permissions of the key file
            chmod 0400 ~/.ssh/$SSH_KEY_ID

      - run:
          name: Add ssh host to known hosts
          command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
        
      - run:
          name: Install rsync
          command: |
            sudo apt update
            sudo apt install rsync
      - run:
          name: Deploy Over SSH
          # rsync -avz -e "ssh -i ~/.ssh/$SSH_KEY_ID" --progress ~/from_directory $SSH_USER@$SSH_HOST:~/target_directory
          # -a option is for archiving the files and subdirectories to preserve everything and then transfer using the recursion method.
          # -v option is for verbose output. By using this option, we can have more information about transfer instead of the silent transfer.
          # Z option compresses the whole data, reduces the file sizes, and transfers the data to the destination system. It comes in handy while transferring a huge amount of data over a slow internet connection.
          # So, collectively, using this combination of options(-avz), you will have the secure and quick file transfer due to the -a and -z options, while using the -v option, you will have a side-by-side a good amount of information about the transfer.
          command: |
            rsync -avz -e "ssh -i ~/.ssh/$SSH_KEY_ID" --progress << pipeline.parameters.workingdir >>/ $SSH_USER@$SSH_HOST:~/$PROJECT_DIRECTORY
      # - run: ssh -i ~/.ssh/$SSH_KEY_ID $SSH_USER@SSH_HOST 'chmod -R 755 ~/$PROJECT_DIRECTORY'

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master