version: 2.1

executors:
  my-executor:
    resource_class: small
    docker:
      - image: cimg/base:2022.09

jobs:
  build:
    executor: my-executor
    working_directory: ~/r

    steps:
      - checkout

      - persist_to_workspace:
          root: "~"
          paths:
            - ./
  deploy:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ./
      - run: mkdir -p ~/.ssh
      - run:
          name: Add ssh key
          command: |
            cat $SSH_KEY_KEY >> ~/.ssh/$SSH_KEY_ID
      - run: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Install rsync
          command: |
            sudo apt update
            sudo apt install rsync
      - run:
          name: Deploy Over SSH
          command: |
            rsync -avz -e "ssh -i ~/.ssh/$SSH_KEY_ID $SSH_USER@SSH_HOST" --progress build $SSH_USER@$SSH_HOST:build
      - run: ssh -i ~/.ssh/$SSH_KEY_ID $SSH_USER@SSH_HOST 'chmod -R 755 ~/build'

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master